# Generated by Django 5.2.3 on 2025-08-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the conversation was last activated/paid for.', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the conversation session expires.', null=True),
        ),
    ]
