# Generated by Django 5.2.3 on 2025-07-01 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('property_status', 'Property Status Change'), ('property_favorited', 'Property Favorited'), ('property_price_change', 'Property Price Change'), ('property_rated', 'Property Rated')], help_text='Category of the notification (e.g., property_status, property_favorited).', max_length=50)),
                ('message', models.TextField(help_text='The text content of the notification.')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='The ID of the related object.', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='True if the notification has been read by the recipient.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notification was created.')),
                ('content_type', models.ForeignKey(blank=True, help_text='The content type of the related object (e.g., Property, User).', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(help_text='The user who receives this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
