# Generated by Django 5.2.3 on 2025-08-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_online_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_identity_verified',
            field=models.BooleanField(default=False, help_text="Indicates if the user's identity has been verified by the national institute."),
        ),
        migrations.AddField(
            model_name='profile',
            name='national_id_number',
            field=models.CharField(blank=True, help_text='National identity number for verification purposes.', max_length=20, null=True, unique=True),
        ),
    ]
