# Generated by Django 5.2.5 on 2025-08-10 22:59

import users.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_identity_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_id_number',
            field=users.fields.EncryptedCharField(blank=True, help_text='Encrypted national identity number for verification purposes.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=users.fields.EncryptedCharField(blank=True, help_text='Encrypted phone number.', max_length=15, null=True),
        ),
    ]
