# Generated by Django 5.2 on 2025-04-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationcode',
            old_name='expires_at',
            new_name='expiry',
        ),
        migrations.RemoveField(
            model_name='verificationcode',
            name='tries_left',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='max_attempts',
            field=models.IntegerField(default=5),
        ),
    ]
