# Generated by Django 5.2 on 2025-04-27 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_expires_at_verificationcode_expiry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='passwordhistory',
            old_name='password',
            new_name='hashed_password',
        ),
    ]
