# Generated by Django 5.2.1 on 2025-05-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_favoriteproperty_property_and_more'),
        ('users', '0007_profile_birth_date_profile_country_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_properties',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', through='properties.FavoriteProperty', to='properties.property'),
        ),
    ]
