# Generated by Django 5.2.1 on 2025-06-15 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteproperty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_property_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoriteproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_relations', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyfacility',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.facility'),
        ),
        migrations.AddField(
            model_name='propertyfacility',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_facilities', to='properties.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='facilities',
            field=models.ManyToManyField(related_name='properties', through='properties.PropertyFacility', to='properties.facility'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteproperty',
            unique_together={('user', 'property')},
        ),
        migrations.AlterUniqueTogether(
            name='propertyfacility',
            unique_together={('property', 'facility')},
        ),
    ]
