# Generated by Django 5.2.1 on 2025-06-15 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('owner', 'ptype', 'city', 'area', 'price'), name='unique_property'),
        ),
    ]
