# Generated by Django 5.2.3 on 2025-06-30 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_active_property_bathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating of the property (0.00 to 5.00)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
