# Generated by Django 5.2.3 on 2025-07-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of individual ratings submitted for this property.'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_rating_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all individual rating values submitted for this property.', max_digits=10),
        ),
    ]
