# Generated by Django 5.2.3 on 2025-07-04 21:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_rating_count_property_total_rating_sum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(help_text='The rating value (1-5 stars).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Property Rating',
                'verbose_name_plural': 'Property Ratings',
            },
        ),
        migrations.RemoveConstraint(
            model_name='property',
            name='unique_property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_rating_sum',
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('owner', 'ptype', 'city', 'area', 'price', 'number_of_rooms', 'bathrooms', 'active', 'is_for_rent', 'longitude', 'latitude'), name='unique_property'),
        ),
        migrations.AddField(
            model_name='rating',
            name='property',
            field=models.ForeignKey(help_text='The property being rated.', on_delete=django.db.models.deletion.CASCADE, related_name='individual_ratings', to='properties.property'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(help_text='The user who provided this rating.', on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'property')},
        ),
    ]
