# Generated by Django 5.2.3 on 2025-08-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_rating_remove_property_unique_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_owner_verified',
            field=models.BooleanField(default=False, help_text="Indicates if the property owner's relationship to this property has been officially verified."),
        ),
        migrations.AddField(
            model_name='property',
            name='property_registry_number',
            field=models.CharField(blank=True, help_text='Official registration number of the property from the national institute.', max_length=50, null=True, unique=True),
        ),
    ]
